/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RelayGuideRouteImport } from './routes/relay-guide'
import { Route as MyHealthRouteImport } from './routes/my-health'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CausalPathwaysRouteImport } from './routes/causal-pathways'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RelayGuideRoute = RelayGuideRouteImport.update({
  id: '/relay-guide',
  path: '/relay-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHealthRoute = MyHealthRouteImport.update({
  id: '/my-health',
  path: '/my-health',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CausalPathwaysRoute = CausalPathwaysRouteImport.update({
  id: '/causal-pathways',
  path: '/causal-pathways',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/causal-pathways': typeof CausalPathwaysRoute
  '/insights': typeof InsightsRoute
  '/library': typeof LibraryRoute
  '/my-health': typeof MyHealthRoute
  '/relay-guide': typeof RelayGuideRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/trust': typeof TrustRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/causal-pathways': typeof CausalPathwaysRoute
  '/insights': typeof InsightsRoute
  '/library': typeof LibraryRoute
  '/my-health': typeof MyHealthRoute
  '/relay-guide': typeof RelayGuideRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/trust': typeof TrustRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/causal-pathways': typeof CausalPathwaysRoute
  '/insights': typeof InsightsRoute
  '/library': typeof LibraryRoute
  '/my-health': typeof MyHealthRoute
  '/relay-guide': typeof RelayGuideRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/trust': typeof TrustRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/causal-pathways'
    | '/insights'
    | '/library'
    | '/my-health'
    | '/relay-guide'
    | '/reports'
    | '/settings'
    | '/simulator'
    | '/trust'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/causal-pathways'
    | '/insights'
    | '/library'
    | '/my-health'
    | '/relay-guide'
    | '/reports'
    | '/settings'
    | '/simulator'
    | '/trust'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/causal-pathways'
    | '/insights'
    | '/library'
    | '/my-health'
    | '/relay-guide'
    | '/reports'
    | '/settings'
    | '/simulator'
    | '/trust'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CausalPathwaysRoute: typeof CausalPathwaysRoute
  InsightsRoute: typeof InsightsRoute
  LibraryRoute: typeof LibraryRoute
  MyHealthRoute: typeof MyHealthRoute
  RelayGuideRoute: typeof RelayGuideRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relay-guide': {
      id: '/relay-guide'
      path: '/relay-guide'
      fullPath: '/relay-guide'
      preLoaderRoute: typeof RelayGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-health': {
      id: '/my-health'
      path: '/my-health'
      fullPath: '/my-health'
      preLoaderRoute: typeof MyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causal-pathways': {
      id: '/causal-pathways'
      path: '/causal-pathways'
      fullPath: '/causal-pathways'
      preLoaderRoute: typeof CausalPathwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CausalPathwaysRoute: CausalPathwaysRoute,
  InsightsRoute: InsightsRoute,
  LibraryRoute: LibraryRoute,
  MyHealthRoute: MyHealthRoute,
  RelayGuideRoute: RelayGuideRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
